export const OTPValidationTime = 1000 * 60 * 2;
export const signinWrongAttemptLimit = 3;
export const signinBlockTime= 1000*60*1

export const plans = [
  {
    planID: "starter",
    title: "Starter Plan",
    price: 299,
    credits: 500,
    validity:1,
    dailyLimit: 50,
    isRecommended: false,
    seoDataCredit: 5,
    thumbnailCredit: 20,
    features: [
      "Plan validity for 1 Month",
      "Per-day max credit limit: 50 Credits",
      "SEO Data Generation available",
      "Thumbnail Generation available",
      "Standard generation priority",
      "Export metadata in JSON format",
    ],
  },
  {
    planID: "pro",
    title: "Pro Creator",
    subtitle: "Best choice for active channel managers",
    price: 599,
    credits: 1500,
    validity: 2,
    dailyLimit: 100,
    isRecommended: true,
    badgeText: "RECOMMENDED",
    seoDataCredit: 5,
    thumbnailCredit: 20,
    features: [
      "Plan validity for 2 Months",
      "Per-day max credit limit: 100 Credits",
      "SEO Data Generation available",
      "Thumbnail Generation available",
      "Accelerated generation priority",
      "CTR-optimized title & tag engine",
    ],
  },
  {
    planID: "growth",
    title: "Growth Studio",
    subtitle: "Built for scaling YouTube channels",
    price: 899,
    credits: 3000,
    validity: 4,
    dailyLimit: 200,
    isRecommended: false,
    seoDataCredit: 5,
    thumbnailCredit: 20,
    features: [
      "Plan validity for 4 Months",
      "Per-day max credit limit: 200 Credits",
      "SEO Data Generation available",
      "Thumbnail Generation available",
      "High-priority generation queue",
      "Multi-variation prompt canvas",
    ],
  },
  {
    planID: "elite",
    title: "Elite Agency",
    subtitle: "Maximum credits for power creators",
    price: 1999,
    credits: 7000,
    validity: 6,
    dailyLimit: 500,
    isRecommended: false,
    seoDataCredit: 5,
    thumbnailCredit: 20,
    features: [
      "Plan validity for 6 Months",
      "Per-day max credit limit: 500 Credits",
      "SEO Data Generation available",
      "Thumbnail Generation available",
      "VIP ultra-fast generation priority",
      "Dedicated creator support",
    ],
  },
];